### ISSUE TITLE
Improve dependency between services

### ISSUE THREAD

**Issue by yatharthranjan** [RADAR-base/RADAR-Docker#180]
We can do better dependency management in the compose file (eg - using the health check of other service) for different services using something like below  -

```yml
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
```

instead of just 

```yml
    depends_on:
      - db
      - redis
``

This will allow services to start after the other service is running and not just created. Also removes the need for applications to sleep for DBs to start up (as is the case in some services in the current setup).

Ref: https://docs.docker.com/compose/compose-file/compose-file-v2/#depends_on
